services:
  nginx:
    container_name: nginx
    image: nginx:42
    build: ./requirements/nginx/
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception
    restart: on-failure
  
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:42
    env_file:
      - .env
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: ./requirements/wp
    image: wordpress:42
    depends_on:
      - mariadb
    volumes:
      - wordpress_vol:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure

#############
#   BONUS   #
#############
  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp/.
    image: ftp:42
    depends_on:
      - wordpress
    volumes:
      - wordpress_vol:/home/${USER}/ftp/files
    env_file:
      - .env
    ports:
      - "21:21"
      - "20:20"
      - "40000-40005:40000-40005"
    networks:
      - inception
    restart: always

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer/.
    image: adminer:42
    depends_on:
      - mariadb
    ports:
      - "600:80"
    networks:
      - inception
    restart: always

  redis:
    container_name: redis
    build: ./requirements/bonus/redis/.
    image: redis:42
    volumes:
     - wordpress_vol:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

  website:
    container_name: website
    build: ./requirements/bonus/websites/.
    image: website:42
    ports:
      - "3000:3000"
    networks:
      - inception
    restart: always

  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor/.
    image: cadvisor:42
    ports:
      - "8080:8080"
    networks:
      - inception
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always

volumes:
  mariadb_vol:
    name: mariadb_vol
    driver: local
    driver_opts:
      device: /home/${USER}/data/mariadb
      o: bind
      type: none

  wordpress_vol:
    name: wordpress_vol
    driver: local
    driver_opts:
      device: /home/${USER}/data/wordpress
      o: bind
      type: none

networks:
  inception:
    name: inception
    driver: bridge
